name: Run EEG Emotion Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download emotions.csv from GitHub Releases
        run: |
          wget -O emotions.csv https://github.com/neha-369-tes/Emotion-sensing-AGI-II/releases/download/V1/emotions.csv
          echo "First 5 lines of downloaded file:"
          head -n 5 emotions.csv
          echo "File size:"
          ls -lh emotions.csv

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python ver-9.py

      - name: Upload artifacts (model + logs + explainability)
        uses: actions/upload-artifact@v4
        with:
          name: eeg-emotion-artifacts
          path: |
            emotion_model.h5
            model_summary.json
            classification_report.txt
            feature_importance_top50.csv
            group_importance.csv
            family_importance.csv

      - name: Upload artifacts (model + logs + explainability)
        uses: actions/upload-artifact@v4
        with:
          name: eeg-emotion-artifacts
          path: |
            emotion_model.h5
            model_summary.json
            classification_report.txt
            feature_importance_top50.csv
            group_importance.csv
            family_importance.csv
